### ISSUE TITLE
Generator crashes if user does not have a `temporary` directory

### ISSUE THREAD

**Issue by dzzdzzdz** [EleniMarli/recipes_project#1]
<img width="1717" alt="Screenshot 2023-10-29 at 17 04 34" src="https://github.com/EleniMarli/recipes_project/assets/6308056/61824076-818d-4978-9b3f-511bfa33391b">

Nice start to the project. Super!!!! Happy to see this come to life.

One issue I had was that I needed to manually create the path/file on my local machine (see screenshot), but once I fixed it, off I went to REWE 🥘 This would be a great test to write, to make sure the code [here](https://github.com/EleniMarli/recipes_project/blob/main/main/shopping_list_module.py#L50) 😉 catches this edge case.

**Comment by EleniMarli** [comment]
Thanks a lot for the feedback, really appreciated! 😄 I fixed the bug and improved the unit tests 💪
